name: test
on: push
jobs:
  test:
    runs-on: ${{ matrix.os-name }}-latest
    strategy:
      matrix:
        os-name: [ ubuntu, windows, macos ]
        configuration: [ Debug, Release ]
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: setup python # for testing purposes
        uses: actions/setup-python@v2
      - name: setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x
      - name: build
        shell: bash
        run: |
          dotnet build -c ${{ matrix.configuration }}
      - name: test
        shell: bash
        run: |
          dotnet test -c ${{ matrix.configuration }}